#!/usr/bin/python3
# SPDX-FileCppyrightText: 2022 Domen Yuta
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0

for line in sys.stdin:
    try: 
         ans += int(line)
    except:
         ans += float(line)

print(ans)

