name: test
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                -uses: action/checkout@v3
                -nsme: All test
                 run: bash -xv ./test.bash
